test and fix

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,4 +1,28 @@
 #!/usr/bin/env bash
 # bin/test <build-dir> <cache-dir> <env-dir>
 
-cd "$1" && dotnet test
+
+### Configure environment
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+set -o nounset    # fail on unset variables
+unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
+
+if [ "$STACK" != "heroku-16" ] && [ "$STACK" != "heroku-18" ]; then
+	echo "Need heroku-16 or heroku-18 stack"
+	exit 1
+fi
+
+### Configure directories
+BUILD_DIR=${1:-}
+CACHE_DIR=${2:-}
+ENV_DIR=${3:-}
+BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
+
+${BP_DIR}/bin/compile "${1}" "${2}" "${3}"
+
+echo ${BUILD_DIR}
+echo ${CACHE_DIR}
+echo ${ENV_DIR}
+
+cd "${1}" && dotnet test
